on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  
  miri:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: miri
    - uses: Swatinem/rust-cache@v2.2.0

    - name: Miri
      run: cargo +nightly miri test --verbose
